#!/usr/bin/env bash
# This script displays information about the subdomains of a given domain

dig_subdomain() {
    local subdomain="$1"
    local domain="$2"
    dig "$subdomain.$domain" +short A | awk '{print $1}'
}

display_info() {
    local subdomain="$1"
    local ip="$2"
    if [ -n "$ip" ]; then
        record_type="A"
    else
        record_type="N/A"
        ip="N/A"
    fi
    echo "The subdomain $subdomain is a $record_type record and points to $ip"
}

if [ -z "$1" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1
subdomains=("www" "lb-01" "web-01" "web-02")

if [ -z "$2" ]; then
    for subdomain in "${subdomains[@]}"; do
        ip=$(dig_subdomain "$subdomain" "$domain")
        display_info "$subdomain" "$ip"
    done
else
    subdomain=$2
    ip=$(dig_subdomain "$subdomain" "$domain")
    display_info "$subdomain" "$ip"
fi
