#!/usr/bin/env bash
# This script displays "To infinity and beyond" with SIGTERM defiance!

trap 'echo "I am invincible!!!"' SIGTERM  # Capture SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

