#!/usr/bin/env bash
# This script displays formatted directory content, excluding hidden files

for file in *; do  
    if [[ -f $file && ! $file =~ ^\.* ]]; then
        filename=$(basename "$file")     
        echo "${filename#*-}”            
    fi
done

